version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '5001:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - monorepo-network

  webapp:
    build:
      context: .
      dockerfile: apps/webapp/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - api
    networks:
      - monorepo-network

networks:
  monorepo-network:
    driver: bridge
